apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kaj3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kaj3
    app.kubernetes.io/part-of: ci10t-776-0017-app
  name: devfile-sample-kaj3xjpn
spec:
  path: /
  port:
    targetPort: 3001
  to:
    kind: Service
    name: devfile-sample-kaj3
    weight: null
status: {}
