apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-kaj3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-kaj3
    app.kubernetes.io/part-of: ci10t-776-0017-app
  name: devfile-sample-kaj3
spec:
  ports:
  - name: "3001"
    port: 3001
    targetPort: 3001
  selector:
    app.kubernetes.io/instance: devfile-sample-kaj3
status:
  loadBalancer: {}
